### ISSUE TITLE
[improvement] Allow multiple composer projects

### ISSUE THREAD

**Issue by Xerkus** [php-vim/phpcd.vim#23]
I would like to be able to work with multiple projects, even simultaneously, without the need to restart nvim.

This will require significant refactor to move away from single channel to allow multiple daemons.

**Comment by lvht** [comment]
Please make your  @imaben  @przepompownia point for https://github.com/phpvim/phpcd.vim/pull/26 and https://github.com/phpvim/phpcd.vim/pull/25. Thanks :smile:
