### ISSUE TITLE
[improvement] Special case handling for container interop

### ISSUE THREAD

**Issue by Xerkus** [php-vim/phpcd.vim#42]
Special case handling might be useful for variables obtained by calling `get` on instance of `Interop\Container\ContainerInterface`. 

Consider following code:

``` php
/**
 * @var Interop\Container\ContainerInterface $container
 */
$container;

$someObject = $container->get(SomeClass::class);
$someObject->...
$otherObject = $container->get(LoggerInterface::class);
$otherObject->...
```

when container entry identifier is  based on class/interface name, we can usually expect returned value to be of that type. It would be nice if phpcd could resolve this specific case and provide autocompletion.

**Comment by lvht** [comment]
[Here](https://github.com/phpvim/phpcd.vim/blob/master/autoload/phpcd.vim#L665-L670) is an example to support the Laravel's 
```
$someObject = app(SomeClass::class);
```
Usage. It's works but ugly. Maybe a plugin mechanism is needed.

**Comment by lvht** [comment]
Added at 59f8d341f34c023bc467c7ede1f6c16b199e4b58
