### ISSUE TITLE
如何设置可以自动触发补全？

### ISSUE THREAD

**Issue by foursking** [php-vim/phpcd.vim#62]
求教如何让插件能够自动触发 php补全？补充下，我安装完，ctrl-]  无法像视频中那样进行跳转？是否需要进行tags文件生成？

**Comment by imaben** [comment]
自动触发补全可以安装一个YouCompleteMe或类似的插件。插件依靠的是php的反射机制来实现跳转、补全的，ctrl-]无法跳转请检查项目是否是以composer来管理依赖的，需要有一个autoload.php文件,或手动执行一次composer dump-autoload
