### ISSUE TITLE
Deoplete sources support

### ISSUE THREAD

**Issue by wsdjeg** [php-vim/phpcd.vim#68]
Thanks for create this plugin for php, I want add these to Spacevim, but I can not find deoplete source , even though deoplete support omni sources, but it will be better, if phpcd has a deoplete sources.

**Comment by lvht** [comment]
Please read `:h g:deoplete#omni_patterns` (or even `:h deoplete.txt`) first. :smile: 

If you really know what are you doing, you could put the following lines into you vimrc file:
```viml
let g:deoplete#omni_patterns = {}
let g:deoplete#omni_patterns.php = '->\|::'
```

As both deoplete and phpcd.vim support the **omnifunc**, there is nothing to do to make deoplete support phpcd.vim.

 If you have an Plug named **XXX** supporting the completion of language **XXX**, what you need to do is just set the `deoplete#omni_patterns.xxx` variable to let deoplete to auto trigger the omnifunc. And if you do not have deoplete, the <kbd>C-x</kbd><kbd>C-o</kbd> is your friend.

**Comment by wsdjeg** [comment]
I know the omni sources works well, and I think you can have a look at javacomplete 2,  there is a issue about why we add deoplete source instead of using omni.
And if you think it is uesful, please reopen this issue.

**Comment by wsdjeg** [comment]
Omni is not really async ,use javacomplete2 source make deoplete more fast.

**Comment by wsdjeg** [comment]
@lvht you can have a look at my fork, I will push the deoplete source.

**Comment by lvht** [comment]
@wsdjeg sorry for misunderstanding. But I am not familiar with deoplete. PR is welcomed 😄

**Comment by wsdjeg** [comment]
Thanks, I will try to do it.
